#!/bin/bash

# define constants
CURR_FILE="${BASH_SOURCE[0]}"
CURR_DIR="$( cd "$( dirname "$CURR_FILE" )" && pwd )"
PROJECT_NAME="$(basename $CURR_DIR)_$(basename $CURR_FILE)"
SESSION_NAME="${PROJECT_NAME%%.*}"
[[ -f "tmux-launch" ]] && LIB_DIR="$CURR_DIR" || LIB_DIR="/etc/aktos/service-runner"

echo "session name: $SESSION_NAME"
exit

# include lib(s)
source "${LIB_DIR}/tmux-launch"

# change working directory
cd /var/www

# start new tmux session (if there is no duplicate)
start-tmux-session "$SESSION_NAME"

# run commands in tmux session
run-in-tmux "ls"
run-in-tmux "top"
run-in-tmux "cd .." "ls -l"

# Show in terminal if not `--headless`
attach-tmux-session "$SESSION_NAME"
