#!/bin/bash
set -eu -o pipefail
safe_source () { [[ ! -z ${1:-} ]] && source $1; _dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; _sdir=$(dirname "$(readlink -f "$0")"); }; safe_source
# end of bash boilerplate

script=$(readlink -f $1)

cat <<EOL
Add the following lines to /etc/rc.local:

echo "Starting $script"
sudo -i -u $(whoami) $script --background

EOL
